### ISSUE TITLE
Checklist for Maintenance PRs

### ISSUE THREAD

**Issue by steelbrain** [steelbrain/todo#11]
Gonna keep this open always. 

- [ ] flow
- [ ] eslint
- [ ] run flow in CI
 -[ ] flow ignore `lib`
- [ ] ucompiler -> babel-cli
- [ ] `.ucompiler.json` -> `.`
- [ ] add flow `decls` if necessary
- [ ] un flow ignore `node_modules`
- [ ] add for-of-efficient to preset if necessary
- [ ] npm ignore `.flowconfig`, `spec` and `.DS_Store` files
